### ISSUE TITLE
3D sequence ribbon plot and trajectory export

### ISSUE THREAD

**Issue by jecfnc** [OpenAero/main#183] opened 2015-06-11 09:11 UTC
I recently discovered OpenAero and it seems to be a great tool, well thought-out.  I have a suggestion for an extra feature that would significantly extend functionality and broaden the remit of the tool.

It would be great if the schematic sequences could be converted into a scaled 3d trajectory ribbon with exportable position vector, orientation vector, velocity vector and roll angle as time series.  

Having the ribbon plotted in 3d to scale would help plan how the sequence maps to ground features and show whether it was feasible to do it within a given display box or spectator field of view.  The plot would benefit from 'rotate' controls and from colour-coding the ribbon with speed, and could ultimately include satpic imagery (think google maps) as an underlay with possible markup to show the box limits, spectator location, or crowdline.

The trajectory export feature would be of great interest as it would enable plotting and manipulation in other software environments or visualisation tools.  For illustration, it would make it possible for other software to read in the trajectory time-series data and ask at each point along it 'what would it mean for spectators if X happened at this point', where X is some form of failure or accident.  This would require more input detail than at present (e.g. planned speeds, standard turn radii/accelerations and height gain/loss schedules for standand figures with a given aircraft type) but these could be optional if the user only wanted the figure sequence.

**Comment by OpenAero** [comment] 2015-06-13 06:06
Duplicate of #152

**Closed by OpenAero** 2015-06-13 06:06 UTC
