### ISSUE TITLE
Add figure string to grid box

### ISSUE THREAD

**Issue by nickbuck** [OpenAero/main#180] opened 2015-04-29 11:08 UTC
When creating a Free Unknown figure set it would be helpful to show the individual figure string in each Grid box when this is printed. This would help sequence designers who have only the print-out of the Grid of figures to ensure that their figures are all exactly correct.

**Comment by OpenAero** [comment] 2015-05-01 08:53
This is possible, but would not guarantee correctness for all figures. Consider the following example:
In the Grid, all figures start on the X axis. So a humpty bump with 1/4 rolls up and down, continuing in same direction would be "4b4>". However, when the same figure is started on Y axis the correct string is "4b4^". The string "4b4>" would give a direction reversing bump.
A solution could be to present two strings in relevant cases. One for starting on X axis and one for starting on Y axis.

**Comment by OpenAero** [comment] 2015-11-19 13:47
To resolve the issue mentioned above, and others. A new system could be made to indicate directionality.
One way could be to add a special code before vertical roll groups that change the figure axis to one previously used. The code would then indicate if this axis was travelled in the same or opposite direction.
The { and } characters are available and could be used for this purpose.
The exact mechanism should be well thought out to be future proof and as much as possible compatible with current notation.

**Comment by OpenAero** [comment] 2018-01-23 17:56
Closing this issue. The problem is not one that appears a lot and the proposed solution is complex.
Also, the expectation is more and more use will be made of graphical editing instead of sequence text editing.

**Closed by OpenAero** 2018-01-23 17:56 UTC
