### ISSUE TITLE
Figures 7.4.6.1-4 are being converted as rolls, not treated as base figures

### ISSUE THREAD

**Issue by Bdavy92960** [OpenAero/main#260] opened 2023-01-31 19:11 UTC
Figures 7.4.6.1-4 are all being converted to 7.4.6.1-4 by the qtrs conversion (or any variant I create of that).  It looks like the basefigure number for those figures isn’t getting clipped off when the rules are processed.  Since those figures cannot have any roll elements, I thought it might be related to that, but the Family 3 figures (same situation, no rolls) are converted fine.  Its causing an alert on the number of rolls whenever figures 7.4.6.1-4 are selected.

This appears to be created by having default rules to check rolls on figures with no allowable rolls .  I'm excepting those figures (Family 2, Family 3, Family 7.4.6) in the rules files from those default rules to eliminate the alert.

**Comment by OpenAero** [comment] 2023-02-01 10:00
Caused by an update in 2023.1.3. Fixed in 2023.3.2.

**Closed by OpenAero** 2023-02-01 10:00 UTC
